name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: test_llm_layer_split
store:
  layers: [11, 10, 9]
  dir: data_mine/${data.name}/bert-${llm_ver}-split
load:
  save_dir: null
  model_only: true
  strict: true
  wait: false
policy:
  device: gpu
  batch_size: 64
