name: ${exp.mode}
dir: saving/${data_sd.name}/${model_sd.name}/patience_${patience}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: train_test
load:
  save_dir: ${load_path}$
  epochs: null
  model_only: true
  strict: false
  wait: false
store:
  metric: GAUC
  maximize: true
  top: 1
  early_stop: ${patience}$
policy:
  epoch_start: ${epoch_start}$
  epoch: 50
  lr: ${lr}$
  item_lr: ${item_lr}$
  freeze_emb: false
  pin_memory: false
  epoch_batch: ${epoch_batch}$
  batch_size: ${batch_size}$
  accumulate_batch: ${acc_batch}$
  device: gpu
  n_warmup: ${warmup}$
  check_interval: -2
  simple_dev: ${simple_dev}$
metrics:
  - GAUC
  - MRR
  - NDCG@1
  - NDCG@5
  - NDCG@10